# For Renaming images

In [ ]:
import os
path=os.chdir("/Users/jvmohanakrishnainty/Desktop/mini project/Bus1_100_images")
i=1
for file in os.listdir(path):
    new_file_name="bus1_{}.jpg".format(i)
    os.rename(file,new_file_name)
    i=i+1

# For resizing and converting images into gray scale

In [ ]:
import cv2

In [2]:

import cv2
for i in range(1,101):
    img=cv2.imread('/Users/jvmohanakrishnainty/Desktop/mini project/Bus1_100_images/bus1_{}.jpg'.format(i),0)
    reimg=cv2.resize(img,(256,256))
    status=cv2.imwrite(r'/Users/jvmohanakrishnainty/Desktop/mini project/Bus1_100_grayresizedimages/bus1_{}.jpg'.format(i),reimg)
    print("Image written to file-system:",status)
    cv2.destroyAllWindows()


Image written to file-system: True
Image written to file-system: True
Image written to file-system: True
Image written to file-system: True
Image written to file-system: True
Image written to file-system: True
Image written to file-system: True
Image written to file-system: True
Image written to file-system: True
Image written to file-system: True
Image written to file-system: True
Image written to file-system: True
Image written to file-system: True
Image written to file-system: True
Image written to file-system: True
Image written to file-system: True
Image written to file-system: True
Image written to file-system: True
Image written to file-system: True
Image written to file-system: True
Image written to file-system: True
Image written to file-system: True
Image written to file-system: True
Image written to file-system: True
Image written to file-system: True
Image written to file-system: True
Image written to file-system: True
Image written to file-system: True
Image written to fil

# For converting images into numpy array 

In [3]:
from matplotlib.image import imread
import numpy as np
bus1_ls=[]
bus2_ls=[]
bus3_ls=[]
path1="/Users/jvmohanakrishnainty/Desktop/mini project/Bus1_100_grayresizedimages/bus1_{}.jpg"
path2="/Users/jvmohanakrishnainty/Desktop/mini project/Bus2_100_grayresizedimages/bus2_{}.jpg"
path3="/Users/jvmohanakrishnainty/Desktop/mini project/Bus3_100_grayresizedimages/bus3_{}.jpg"
x_ls=[]
for i in range(1,101):
    img1=imread(path1.format(i))
    x_ls.append(img1)
for i in range(1,101):
    img2=imread(path2.format(i))
    x_ls.append(img2)
for i in range(1,101):
    img3=imread(path3.format(i))
    x_ls.append(img3)
    

In [11]:
x_ls=np.asarray(x_ls)
print(x_ls.shape)
x_np=x_ls.reshape(300,256*256)
print(x_np.shape)
print(x_np.ndim)
print(type(x_np))

(300, 256, 256)
(300, 65536)
2
<class 'numpy.ndarray'>


In [7]:
y_ls=[]
for i in range(0,100):
    y_ls.append(1)
for i in range(0,100):
    y_ls.append(2)
for i in range(0,100):
    y_ls.append(3)
print(len(y_ls))

300


In [13]:
print(x_np[1].shape)

(65536,)


In [4]:
y_np=np.asarray(y_ls)
print(y_np.ndim)
y_np=y_np.reshape(300,1)
print(y_np.ndim)

1
2


In [5]:
print(y_np)

[[1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]


In [7]:
print(x_np.ndim)
print(y_np.ndim)

2
2


# Splitting into test and train data

In [8]:
from sklearn.model_selection import train_test_split
from sklearn import metrics 

In [9]:
X_train, X_test, y_train, y_test = train_test_split(x_np,y_np,test_size=0.20,shuffle=True, random_state= 19)


In [ ]:
print(X_train.ndim)
print(y_train.ndim)

# Model training  

# Using Random Forest

In [21]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators = 200)  
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
print("ACCURACY OF THE MODEL: ", metrics.accuracy_score(y_test, y_pred))

/Users/jvmohanakrishnainty/anaconda3/lib/python3.11/site-packages/sklearn/base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


ACCURACY OF THE MODEL:  0.8333333333333334


In [22]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_pred))

[[16  2  0]
 [ 2 14  2]
 [ 2  2 20]]


# Using SVM

In [23]:
from sklearn.svm import SVC
SVCClf = SVC(kernel = 'rbf',gamma = 'scale', shrinking = False,)
SVCClf.fit(X_train, y_train)
y_pred = SVCClf.predict(X_test)
print("ACCURACY OF THE MODEL: ", metrics.accuracy_score(y_test, y_pred))

/Users/jvmohanakrishnainty/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


ACCURACY OF THE MODEL:  0.7833333333333333


In [24]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_pred))

[[15  3  0]
 [ 0 16  2]
 [ 2  6 16]]


# Using Decision Tree

In [25]:
#Fitting Decision Tree classifier to the training set  
from sklearn.tree import DecisionTreeClassifier  
classifier= DecisionTreeClassifier(criterion='entropy', random_state=0)  
classifier.fit(X_train, y_train)  
y_pred= classifier.predict(X_test) 
from sklearn.metrics import confusion_matrix 
cm= confusion_matrix(y_test, y_pred) 
print("Accuracy:",metrics.accuracy_score(y_test,y_pred))

Accuracy: 0.5333333333333333


In [26]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_pred))

[[10  7  1]
 [ 8  7  3]
 [ 7  2 15]]


# Using Naive Bayes

In [27]:
# training the model on training set
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, y_train)
 
# making predictions on the testing set
y_pred = gnb.predict(X_test)
 
# comparing actual response values (y_test) with predicted response values (y_pred)
from sklearn import metrics
print("Gaussian Naive Bayes model accuracy(in %):", metrics.accuracy_score(y_test, y_pred)*100)

Gaussian Naive Bayes model accuracy(in %): 66.66666666666666


/Users/jvmohanakrishnainty/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [28]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_pred))

[[13  5  0]
 [ 3 12  3]
 [ 4  5 15]]


# Using KNN

In [34]:
from sklearn import neighbors, datasets, preprocessing
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
scaler = preprocessing.StandardScaler().fit(X_train)
Xtrain = scaler.transform(X_train)
Xtest = scaler.transform(X_test)

knn = neighbors.KNeighborsClassifier(n_neighbors=4)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)

print("Acurracy: "+str(accuracy_score(y_test, y_pred)))
print()
#print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

Acurracy: 0.75

[[15  2  1]
 [ 3 12  3]
 [ 4  2 18]]


/Users/jvmohanakrishnainty/anaconda3/lib/python3.11/site-packages/sklearn/neighbors/_classification.py:228: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


# For Saving Model 

In [ ]:
from joblib import Parallel, delayed
import joblib
  
  
# Save the model as a pickle in a file
joblib.dump(clf, 'file.pkl')
  
# Load the model from the file
clf_from_joblib = joblib.load('file.pkl')
  
# Use the loaded model to make predictions
#clf_from_joblib.predict(X_test)

# For connecting Database 

In [1]:
import mysql.connector
dataBase = mysql.connector.connect(
  host ="localhost",
  user ="root",
  passwd ="krishna@inty",
  database="miniproject"
)
 
# preparing a cursor object
cursorObject = dataBase.cursor()

# For User Interface 

In [2]:
import gradio as gr
import numpy as np
from joblib import Parallel, delayed
import joblib
import cv2
from datetime import datetime


def image(img,status,clear_data,save):    
    if(clear_data):
        cursorObject.execute("delete from busdb")
    img=cv2.resize(img,(256,256))
    img=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    x_np=np.array(0)
    x_np=np.array(img)
    x=x_np.reshape(1,65536)
    clf_from_joblib = joblib.load('filename.pkl')
    res=clf_from_joblib.predict(x)  
    sql = "INSERT INTO busdb (Name,Status,Time)\
VALUES (%s,%s,%s)"
    s=status+" at"
    now = datetime.now()
    id = "Bus "+str(res[0])
    formatted_date = now.strftime('%Y-%m-%d %H:%M:%S')
    val=(id,s,formatted_date)
    
    cursorObject.execute(sql, val)
    dataBase.commit()
    cursorObject.execute("select * from busdb")
    a=cursorObject.fetchall()
    y="";
    for i in a:
        for j in i:
            y=y+j+"  "
        y=y+"\n"
    if(save):
        f = open("/Users/jvmohanakrishnainty/Desktop/"+formatted_date, "a")
        for i in a:
            s=""
            for j in i:
                s=s+j+" "
            s=s+"\n"
            f.write(s)
        f.close()
        
    
    return ("Bus "+str(res[0])+" "+status,y)
    
#For uploading image       
tab1 = gr.Interface(fn=image, 
inputs=["image",
gr.Radio(["Entered", "Exited"], label="Status", info="Did vehicle Entered or Exit"),
gr.Checkbox(label="Clear Data", info="Do you want to clear previous records?"),
gr.Checkbox(label="Save", info="Do you want to save the data?")],
outputs=["text","text"])

#For Taking photo
tab2 = gr.Interface(fn=image, 
inputs=[gr.Image(source="webcam"),
gr.Radio(["Entered", "Exited"], label="Status", info="Did bus Entered or Exit"),
gr.Checkbox(label="Clear Data", info="Do you want to clear previous records?"),
gr.Checkbox(label="Save", info="Do you want to save the data?")],
outputs=["text","text"])
 
    
if __name__ == "__main__":
    demo = gr.TabbedInterface([tab1, tab2], ["Upload image", "Take Photo"])
    demo.launch(auth=('vasavi','1234'))   

/Users/jvmohanakrishnainty/anaconda3/lib/python3.11/site-packages/gradio/blocks.py:1032: UserWarning: api_name predict already exists, using predict_1
  warnings.warn(


Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
